version: '3.9'

services:
  web:
    container_name: burgerzillalatest
    image: burgerzillalatest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/burgerzilla
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=burgerzilla
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}